### ISSUE TITLE
[Feature Request] Different Author on each card

### ISSUE THREAD

**Issue by monyarm** [piface314/ygo-fabrica#4]
I've made a hacky solution that adds another column to the cdb, and uses that to get the necessary info, but it's obviously not the best option.
I'd like an author or artist field for the cards, in order to be able to credit the artist of the art i'm using.

**Comment by piface314** [comment]
I've been thinking about this strategy of adding another column (or maybe a table) in the database for information unrelated to EDOPro, like author, year, set number (ABCD-XY012), etc. If additional data does not conflict with the simulator, this feature is going to be included eventually.

**Comment by monyarm** [comment]
Well from what i've seen it doesn't conflict, i've added an author column, and there has been no issue with EDOPro, as it just ignores columns that aren't used/

**Comment by piface314** [comment]
Actually I noticed that while adding columns to the `texts` table is not a problem, adding a column to `datas` does _unwanted_ things to the game. That's because the query used to load the data is:
```sql
select * from datas,texts where datas.id=texts.id ORDER BY texts.id;
```
I honestly don't know why that `ORDER BY` is there or why a NATURAL JOIN wasn't used, but anyway, since an `*` is used, all columns from `datas` are retrieved, and thus, if you add a column to `datas`, the column indexes for the other table are "shifted" (i.e. `id` becomes `name`, `name` becomes `str1`, `str1` becomes `str2`, and so on) 

So in order to avoid this problem altogether, I'll add a table just for that, so the original structure isn't touched at all. Future proofing :)
